const express=require('express')
const srv=express()
const todorouter=require('./router/todo')
srv.use(express.json())
srv.use(express.urlencoded({extended:true}))
srv.set('view engine','hbs')
srv.set('views',__dirname + "/view")
srv.use('/todos',todorouter)
srv.listen(9894)